if(EXISTS "/home/runner/work/tomport/tomport/_codeql_build_dir/tomport_unit_tests[1]_tests.cmake")
  include("/home/runner/work/tomport/tomport/_codeql_build_dir/tomport_unit_tests[1]_tests.cmake")
else()
  add_test(tomport_unit_tests_NOT_BUILT tomport_unit_tests_NOT_BUILT)
endif()
